version: '3.9'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=autos;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autos
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  reports:
    build:
      context: ./reports
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=autos;Username=postgres;Password=postgres
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - reports

volumes:
  db_data:
